name: Initialize Terraform
description: Preapre for executing Terraform CLI.
runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Init and get modules
      shell: bash
      run: |
        terraform init
        terraform get
