name: Plan and Apply Terraform
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Run formatter
        run: terraform fmt -check
      - name: Init and get modules
        run: |
          terraform init
          terraform get
      - name: Run validator
        run: terraform validate
      - name: Plan
        run: terraform plan
        if: github.event_name == 'pull_request'
        env:
          TF_VAR_discord_token: ${{ secrets.DISCORD_TOKEN }}
