name: Plan and Apply Terraform
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform fmt -check
      - run: |
          terraform init
          terraform get
      - run: terraform validate -no-color
      - run: terraform plan -no-color
        env:
          TF_VAR_discord_token: ${{ secrets.DISCORD_TOKEN }}
