name: Update channels.md in Kagerou-Discord/docs
on:
  push:
    branches:
      - main
    paths:
      - text_ch.tf
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run workflow
        run: gh workflow run update-ch.yml --repo Kagerou-Discord/docs --ref main
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
